export const SAVE_COCTAILS_LIST = "SAVE_COCTAILS_LIST";
export const SAVE_FILTERS_LIST = "SAVE_FILTERS_LIST";
export const ADD_FILTER = "ADD_FILTER";
export const DELETE_FILTER = "DELETE_FILTER";
export const REFRESH_FILTERS_LIST = "REFRESH_FILTERS_LIST";